Adding control on file access

diff --git a/bin/helenasyncd b/bin/helenasyncd
--- a/bin/helenasyncd
+++ b/bin/helenasyncd
@@ -16,17 +16,6 @@ PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 # Short-Description: a service that provides automated, command-line syncing
 ### END INIT INFO
 
-#DAEMON=/usr/local/bin/lsyncd
-#NAME=helenasync
-#DESC="a service that provides command-line, automated syncing between systems"
-#LOGLEVEL=scarce
-#DELAY_SEC=2
-#USER_NAME=fullbright
-#REMOTE_USER_NAME=sergio
-#CONF_FILE=/home/$USER_NAME/.$NAME/helenasync.lua
-#LOGFILE=/home/$USER_NAME/.$NAME/$NAME.log
-#PIDFILE=/home/$USER_NAME/.$NAME/$NAME.pid
-
 PARAM_CONF_FILE=/opt/helenasync/conf/helenasync.conf
 
 ######
@@ -34,6 +23,8 @@ PARAM_CONF_FILE=/opt/helenasync/conf/helenasync.conf
 ######
 if [ -e $PARAM_CONF_FILE ]; then
         . $PARAM_CONF_FILE
+else
+	echo "****** ERROR ******* : The configuration file $PARAM_CONF_FILE does not exist !"
 fi
 
 ######
@@ -68,66 +59,92 @@ set -e
 case "$1" in
   start)
 	echo -n "Starting $NAME daemon..."
-	#su $RUN_AS_USER -c "$DAEMON -log $LOGLEVEL -delay $DELAY_SEC -logfile $LOGFILE -pidfile $PIDFILE -rsyncssh $LOCAL_DIR $REMOTE_HOST $REMOTE_DIR"
+	
 	echo "Executing command : su $RUN_AS_USER -c '$DAEMON -log $LOGLEVEL -delay $DELAY_SEC -logfile $LOGFILE -pidfile $PIDFILE $CONF_FILE'"
 	su $RUN_AS_USER -c "$DAEMON -log $LOGLEVEL -delay $DELAY_SEC -logfile $LOGFILE -pidfile $PIDFILE $CONF_FILE"
-	#$DAEMON -log $LOGLEVEL -delay $DELAY_SEC -logfile $LOGFILE -pidfile $PIDFILE $CONF_FILE
 	echo "done"
-	#echo `ps -fe | grep "/usr/local/bin/lipsyncd" | grep -v grep | cut -d' ' -f7` > $PIDFILE
+
+	echo "Saving daemon $DAEMON pid file"
 	echo `pidof $DAEMON` > $PIDFILE
-	#echo "====== lipsyncd (pid `cat $PIDFILE`) started on `date` =====" >> $LOGFILE
-	#echo "====== lipsyncd (pid `pidof lipsyncd`) started on `date` =====" >> $LOGFILE
+	echo "====== $DAEMON (pid `cat $PIDFILE`) started on `date` =====" >> $LOGFILE
+	echo "====== $DAEMON (pid `echo  $NAME | xargs pidof`) started on `date` =====" >> $LOGFILE
 	echo "`date "+%a %b %d %T %Y"` Daemon: helenasyncd has started as pid `pidof $DAEMON`" >> $LOGFILE
-	#
+	
+
 	#Starting lipsync updater in a separated thread
-	echo -n "Starting lipsync updater in a separated thread ... "
+	echo "Starting lipsync updater in a separated thread ... "
 	$UPDATER_DAEMON >> $LOGFILE &
-	#echo `pidof $UPDATER_DAEMON` > $UPDATER_PIDFILE
 	eval UPDATER_PID=`ps aux | grep $UPDATER_DAEMON | grep -v grep | awk '{print $2}'`
 	echo $UPDATER_PID > $UPDATER_PIDFILE
 	echo "Done."
 	echo "Updater has started with pid $UPDATER_PID"
-	#
+	
 	#notify startup
 	$NOTIFY_BIN "${NAME} has started."
 	;;
   stop)
+	set +e
 	echo "Stopping $NAME daemon..."
-	#start-stop-daemon --stop --oknodo --quiet --pidfile /var/run/$NAME.pid \ --exec $DAEMON
-	#echo "====== lipsyncd stopped on `date` =====" >> $LOGFILE
 	echo "`date "+%a %b %d %T %Y"` Daemon: helenasyncd is stopping" >> $LOGFILE
 	
 	######## Killing daemon
 	echo "   Killing all $DAEMON ... "
-	echo -n "       Removing PID file for $DAEMON ... "
+	echo "       Removing PID file for $DAEMON ... "
 	if [ -f $PIDFILE ] ; then
+		echo "       PID file found."
+		echo -n "       Killing process with PID `cat $PIDFILE` ... "
+		kill -9 `cat $PIDFILE`		
+		echo "       done."
+
+		echo -n "       Removing PID file ..."
 		rm $PIDFILE
-		echo "done."
-		echo -n "          Killing daemon ... "
-		`killall $DAEMON`
-		echo "done."
+		echo "       done."
+
 	else
-		echo "Fail. $PIDFILE not found."
+		echo "       Fail. $PIDFILE not found."
+		echo "       Trying to kill all $DAEMON processes"
+		NBPROCESS=`ps aux | grep $DAEMON | grep -v grep | wc -l`
+
+		if [ $NBPROCESS -gt 0 ]; then
+			#ps aux | grep $UPDATER_DAEMON | grep -v grep | awk '{print $2}' | xargs kill -9
+			`killall $DAEMON`
+		else
+			echo "       No process found for daemon $DAEMON"
+		fi
+		
+		echo "       done"
 	fi
 	
 	
 	
 	######### Killing updater daemon
 	echo "   Killing all $UPDATER_DAEMON ... "
-	echo -n "       Removing PID file for $UPDATER_DAEMON ... "	
+	echo "       Removing PID file for $UPDATER_DAEMON ... "	
 	if [ -f $UPDATER_PIDFILE ]; then
-		rm $UPDATER_PIDFILE
-		echo "Done."
-		echo -n "          Killing daemon ... "
-		#`killall $UPDATER_DAEMON`
-		#kill -9 `ps aux | grep $UPDATER_DAEMON | grep -v grep | awk '{print $2}'`
-		ps aux | grep $UPDATER_DAEMON | grep -v grep | awk '{print $2}' | xargs kill -9
+		echo "       Pid file found."
+		echo -n "       Killing daemon $UPDATER_DAEMON ... "		
+		kill -9 `cat $UPDATER_PIDFILE`
 		echo "done"
+
+		echo -n "       Pid file found. PID is : `cat $UPDATER_PIDFILE`. Removing ..."
+		rm $UPDATER_PIDFILE
+		echo "       Done."
+
 	else
-		echo "Fail. $UPDATER_PIDFILE not found."
+		echo "       Fail. $UPDATER_PIDFILE not found."
+		echo "       Trying to kill all $UPDATER_DAEMON processes"
+		NBPROCESS=`ps aux | grep $UPDATER_DAEMON | grep -v grep | wc -l`
+
+		if [ $NBPROCESS -gt 0 ]; then
+			ps aux | grep $UPDATER_DAEMON | grep -v grep | awk '{print $2}' | xargs kill -9
+		else
+			echo "       No process found for daemon $UPDATER_DAEMON"
+		fi
+		echo "       done"
 	fi
 	#
 	echo "Done."
+	set -e
 
 	$NOTIFY_BIN "$NAME daemon stopped."
 	;;
diff --git a/bin/lipsync-notify b/bin/lipsync-notify
--- a/bin/lipsync-notify
+++ b/bin/lipsync-notify
@@ -11,6 +11,8 @@ PARAM_CONF_FILE=/opt/helenasync/conf/helenasync.conf
 ###############
 if [ -e $PARAM_CONF_FILE ]; then
         . $PARAM_CONF_FILE
+else
+	echo "****** ERROR ******* : The configuration file $PARAM_CONF_FILE does not exist !"
 fi
 
 SYSTEM=`uname`
@@ -19,7 +21,9 @@ MESSAGE="${1}"
 
 if [ ${SYSTEM} == 'Linux' ]; then
 	if which notify-send > /dev/null; then
+		set +e
   		DISPLAY=:0.0 notify-send --icon=$NOTIFY_ICON --expire-time=1 "$NAME" "${MESSAGE}"
+		set -e
 	elif which zenity > /dev/null; then
 		echo 'message:lipsync '${MESSAGE}'' | DISPLAY=:0.0 zenity --notification --window-icon=$NOTIFY_ICON --listen
 	fi
